[
  {
    created_at: 'Thu Jun 01 16:19:59 +0000 2017',
    id: 870313988021772300,
    id_str: '870313988021772288',
    text: 'Щоб подолати корупцію став лайк і озброюйся маніпуляціями тупих дегенератів про кононенка-грановського',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: 870312406265856000,
    in_reply_to_status_id_str: '870312406265856002',
    in_reply_to_user_id: 2499978518,
    in_reply_to_user_id_str: '2499978518',
    in_reply_to_screen_name: 'hu_lviv',
    user: {
      id: 2499978518,
      id_str: '2499978518',
      name: 'Каменяр',
      screen_name: 'hu_lviv',
      location: 'Lviv',
      description: 'Лупайте сю скалу! Нехай ні жар, ні холод не спинить вас! Зносіть і труд, і спрагу, й голод, бо вам призначено скалу сесю розбить - Іван Франко Каменярі,1878',
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 20957,
      friends_count: 291,
      listed_count: 127,
      created_at: 'Fri May 16 21:57:10 +0000 2014',
      favourites_count: 42346,
      utc_offset: 10800,
      time_zone: 'Kyiv',
      geo_enabled: true,
      verified: false,
      statuses_count: 109672,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'C0DEED',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_tile: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2499978518/1428795875',
      profile_link_color: '4A913C',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 21,
    favorite_count: 31,
    favorited: false,
    retweeted: false,
    lang: 'uk',
  },
  {
    created_at: 'Thu Jun 01 16:13:41 +0000 2017',
    id: 870312406265856000,
    id_str: '870312406265856002',
    text: 'Корупцію подолано! https://t.co/RFrgFvAgnV',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [],
      media: [
        {
          id: 870311922377379800,
          id_str: '870311922377379840',
          indices: [19, 42],
          media_url: 'http://pbs.twimg.com/media/DBP4FREXUAAWSfn.jpg',
          media_url_https: 'https://pbs.twimg.com/media/DBP4FREXUAAWSfn.jpg',
          url: 'https://t.co/RFrgFvAgnV',
          display_url: 'pic.twitter.com/RFrgFvAgnV',
          expanded_url: 'https://twitter.com/hu_lviv/status/870312406265856002/photo/1',
          type: 'photo',
          sizes: {
            large: { w: 717, h: 596, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 680, h: 565, resize: 'fit' },
            medium: { w: 717, h: 596, resize: 'fit' },
          },
        },
      ],
    },
    extended_entities: {
      media: [
        {
          id: 870311922377379800,
          id_str: '870311922377379840',
          indices: [19, 42],
          media_url: 'http://pbs.twimg.com/media/DBP4FREXUAAWSfn.jpg',
          media_url_https: 'https://pbs.twimg.com/media/DBP4FREXUAAWSfn.jpg',
          url: 'https://t.co/RFrgFvAgnV',
          display_url: 'pic.twitter.com/RFrgFvAgnV',
          expanded_url: 'https://twitter.com/hu_lviv/status/870312406265856002/photo/1',
          type: 'photo',
          sizes: {
            large: { w: 717, h: 596, resize: 'fit' },
            thumb: { w: 150, h: 150, resize: 'crop' },
            small: { w: 680, h: 565, resize: 'fit' },
            medium: { w: 717, h: 596, resize: 'fit' },
          },
        },
      ],
    },
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 2499978518,
      id_str: '2499978518',
      name: 'Каменяр',
      screen_name: 'hu_lviv',
      location: 'Lviv',
      description: 'Лупайте сю скалу! Нехай ні жар, ні холод не спинить вас! Зносіть і труд, і спрагу, й голод, бо вам призначено скалу сесю розбить - Іван Франко Каменярі,1878',
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 20957,
      friends_count: 291,
      listed_count: 127,
      created_at: 'Fri May 16 21:57:10 +0000 2014',
      favourites_count: 42346,
      utc_offset: 10800,
      time_zone: 'Kyiv',
      geo_enabled: true,
      verified: false,
      statuses_count: 109672,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'C0DEED',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_tile: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2499978518/1428795875',
      profile_link_color: '4A913C',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 26,
    favorite_count: 26,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'uk',
  },
  {
    created_at: 'Thu Jun 01 15:02:45 +0000 2017',
    id: 870294552971808800,
    id_str: '870294552971808768',
    text: 'Перемога над наркозалежністю стала можливою завдяки тому, що я продавала наркоману наркотики - Ю.Тимошенко https://t.co/lpWseBk4of',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [],
      urls: [
        {
          url: 'https://t.co/lpWseBk4of',
          expanded_url: 'https://twitter.com/Batkivshchyna/status/870280520290140160',
          display_url: 'twitter.com/Batkivshchyna/…',
          indices: [107, 130],
        },
      ],
    },
    source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 2499978518,
      id_str: '2499978518',
      name: 'Каменяр',
      screen_name: 'hu_lviv',
      location: 'Lviv',
      description: 'Лупайте сю скалу! Нехай ні жар, ні холод не спинить вас! Зносіть і труд, і спрагу, й голод, бо вам призначено скалу сесю розбить - Іван Франко Каменярі,1878',
      url: null,
      entities: { description: { urls: [] } },
      protected: false,
      followers_count: 20957,
      friends_count: 291,
      listed_count: 127,
      created_at: 'Fri May 16 21:57:10 +0000 2014',
      favourites_count: 42346,
      utc_offset: 10800,
      time_zone: 'Kyiv',
      geo_enabled: true,
      verified: false,
      statuses_count: 109672,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'C0DEED',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/556387475153633280/muFz9Ri4.jpeg',
      profile_background_tile: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/587040736400379905/fUgYmK1p_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2499978518/1428795875',
      profile_link_color: '4A913C',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'DDEEF6',
      profile_text_color: '333333',
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none',
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 870280520290140200,
    quoted_status_id_str: '870280520290140160',
    quoted_status: {
      created_at: 'Thu Jun 01 14:06:59 +0000 2017',
      id: 870280520290140200,
      id_str: '870280520290140160',
      text: 'Юлія Тимошенко: Перемога у Стокгольмському арбітражі стала можливою завдяки газовому контракту 2009 року… https://t.co/hi6jPGkdju',
      truncated: true,
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [],
        urls: [
          {
            url: 'https://t.co/hi6jPGkdju',
            expanded_url: 'https://twitter.com/i/web/status/870280520290140160',
            display_url: 'twitter.com/i/web/status/8…',
            indices: [106, 129],
          },
        ],
      },
      source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 754753628,
        id_str: '754753628',
        name: 'ВО Батьківщина',
        screen_name: 'Batkivshchyna',
        location: 'Ukraine',
        description: 'Офіційне представництво ВО Батьківщина у Twitter',
        url: 'http://t.co/fYcFpXX6lR',
        entities: {
          url: {
            urls: [
              {
                url: 'http://t.co/fYcFpXX6lR',
                expanded_url: 'http://ba.org.ua/',
                display_url: 'ba.org.ua',
                indices: [0, 22],
              },
            ],
          },
          description: { urls: [] },
        },
        protected: false,
        followers_count: 38735,
        friends_count: 238,
        listed_count: 339,
        created_at: 'Mon Aug 13 08:49:19 +0000 2012',
        favourites_count: 1,
        utc_offset: 10800,
        time_zone: 'Kyiv',
        geo_enabled: true,
        verified: true,
        statuses_count: 11955,
        lang: 'en',
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: 'F1F0EF',
        profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/463632130774278145/0SyLgjBe.png',
        profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/463632130774278145/0SyLgjBe.png',
        profile_background_tile: false,
        profile_image_url: 'http://pbs.twimg.com/profile_images/869848264002195456/L_TF-4YH_normal.jpg',
        profile_image_url_https: 'https://pbs.twimg.com/profile_images/869848264002195456/L_TF-4YH_normal.jpg',
        profile_banner_url: 'https://pbs.twimg.com/profile_banners/754753628/1496223041',
        profile_link_color: 'DA2032',
        profile_sidebar_border_color: 'FFFFFF',
        profile_sidebar_fill_color: 'DDEEF6',
        profile_text_color: '333333',
        profile_use_background_image: false,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: false,
        follow_request_sent: false,
        notifications: false,
        translator_type: 'none',
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 16,
      favorite_count: 20,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: 'uk',
    },
    retweet_count: 107,
    favorite_count: 105,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'uk',
  },
];
